# Generated by Django 3.2.7 on 2022-01-11 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userb2',
            name='history',
            field=models.JSONField(default=set),
        ),
    ]
